### ISSUE TITLE
Adding another if_existing /proc/net/route breaks weather images

### ISSUE THREAD

**Issue by zoof** [zagortenay333/Harmattan#2]
When I modified the .conkrc to add another if/else clause (for whatever reason, my ethernet interface is enp0s20), the weather images broke.  But if I simply edit one of the existing if/else clauses, everything works fine.

**Comment by zagortenay333** [comment]
Mind posting the conkyrc on pastebin?

**Comment by zagortenay333** [comment]
Btw, if all you need is a different network name, then you can just modify an existing one rather than adding new if/else statements.

**Comment by zoof** [comment]
Sure -- it's at: http://pastebin.com/adkaNfhk

Yes, that's what I did when I found the weather images broken.

**Comment by zagortenay333** [comment]
Oh now I see. You need to be careful there.

Notice the voffsets at lines  179, 175, 170, 165, 160 etc...? Each time you add that section, you add 1 new line to the conky (conky renders empty lines) which is about 13px tall with that font.
You need to adjust the voffset for every section you add; instead of 311, your voffset should be (344 + 13).

Also, you forgot to add a `${if_existing /proc/net/route enp0s1}`

**Comment by zoof** [comment]
Ah, I see.  Many thanks!

**Comment by zagortenay333** [comment]
Np!
