### ISSUE TITLE
Blackborder in Gnome shell

### ISSUE THREAD

**Issue by mohanrex** [zagortenay333/Harmattan#3]
I started using your conky module, and i really liked this especially your god mode. But It seems there is a black box behind this module. I can't find any settings related to redesign according to my need. Please provide an steps or show me how to change this. I also read it is an issue in your module. If you could show me a way, may be i could also try this to be fixed.
Even if i use mini or compact or any other module this black box appears to be in full size and it seems to be exist as same as that of other for whatever theme i used.

**Comment by zagortenay333** [comment]
Conky uses fake transparency instead of rgba. It can use rgba, but it has issues with images, so that's why I can't use it in this conky.

The issue with fake transparency is that conky looks up where the wallpaper is to replicate it, but in gnome shell the wallpaper is not where it is on most distros( the root window), so all you get is black.

Only solution is to use something like feh; a program that can draw the wallpaper.

See also question 6 on: http://conky.sourceforge.net/faq.html

**Comment by mohanrex** [comment]
Thanks for the solution.... I'll surely try it out.... May be you should add this in your readme file so that anyone like me would have found the soultion for that problem who uses gnome shell.

**Comment by Vistaus** [comment]
Hmm, feh didn't help in my case under Budgie DE. The black border is still there 😞
