### ISSUE TITLE
Network disconnected message, when it is not.

### ISSUE THREAD

**Issue by Abhinav1217** [zagortenay333/Harmattan#39]
Hi,

I Registered on openweather website and got the API key, then I added my location id, at appropriate place.  Then I logout and logged in, and started conky.  Only personal change I made to conkyrc is that I added `  alignment="top_right",` on line 25 

I am not seeing weather info,  And below that It is saying that "Network disconnected" When actually It is not. Please see the screenshot.

![screenshot from 2017-05-19 18-07-34](https://cloud.githubusercontent.com/assets/740584/26248001/f5c1d1d0-3c8f-11e7-912e-b149be001d39.png)

What should I do?

**Comment by zagortenay333** [comment]
Duplicate of #23 ?

**Comment by ayito** [comment]
I just solved installing "jq" package (using Ubuntu) see issue #42 
hope it helps.

**Comment by ayito** [comment]
Also, check your .conkyrc file, just edit it an search for the string "Network disconnected", I found it at line 245.

> ${voffset -311}${goto 40}${color5}Network disconnected${color}

Then at the lines above I read a series of "${if_existing /proc/net/route ...." you can figure out that's the code that prints out the upspeed and downspeed of the network, check if your network interface is listed in any of the "if's", mine wasn't. I searched for "enp3s0f1" and it just wasn't there. Does it automagically detects the network interfaces or it has to be manually added?

So what i did is add another "if_existing else" block with the name of my interface, then at the end of this section I added another ${endif} to match the number of "if_existing else's" (or you may not need to do this latter thing if instead of copying and adding another if, just replace one of the existing ones).

Anyway, just see the point. Find out your network interface, from the command line:
`$ ifconfig`
also, you can check:
`$ cat /proc/net/route`
and confirm that the network interface is there.

Now everything is working for me.

**Comment by Abhinav1217** [comment]
Sorry I didn't update this. Actually it started working after @zagortenay333  pointed out to the #23 . I Followed the steps there. Although I do wish that there should be easier way to add entry for network driver. Something like the variables used for weather api, There should be a variable for network driver too..

One Thing I haven't figure out is to have a common config file. at this point, whenever I change the theme, I need to enter the variables again.
