### ISSUE TITLE
Feedback: lm-sensors/hddtemp Integration

### ISSUE THREAD

**Issue by VicenteRD** [zagortenay333/Harmattan#5]
I tried adding it myself, but the style goes to sh...
https://distrojumper.wordpress.com/2011/10/15/conky-and-lm-sensors/

Basically, on God-Mode, add CPU temperatures after the uptime.
Also, reading through the conkyrc file, it'd seem that the only CPU usage shown is for cpu0, which would be a single core? What about us quad-core owners ?

Cheers

EDIT: Also, I saw a picture of one of the setups where it shows what the weather should look like, but idk where to turn that on, if that's what I'm missing.

**Comment by zagortenay333** [comment]
I thought about adding lm-sensors before I even released it and decided not to.

I can't even fully remember why, but it probably had something to do with the fact that I wanted  Harmattan to be as easily installed as possible, and with as little distro/comp specific tweaks as possible.
Not to mention what a huge redesign it would be to to apply this to 20+ themes; you've seen how sensitive the style is. XD

As for quad-core users, you'll have to manually add it if you want to; otherwise, I would have to maintain several versions of Harmattan just for that. Instead of doing that, I just used `cpu0` which is the total cpu usage.

I didn't quite understand what you mean in that last part about the weather.

**Comment by VicenteRD** [comment]
This is the weather thing Im talking about: http://goo.gl/7C1YkP

As for the lm sensors, I understand completely. Thanks for explaining it like that... Then again, it'd be great if you helped me add all the stuff xD, but first let me try replacing the processes with it.

**Comment by zagortenay333** [comment]
Still not quite sure what you mean about the weather. Do you mean what mode that is? That is the compact mode; the particular theme is New-Minty, but I have updated it since that screenshot.

I'm afraid I won't be helping you there. I had my fair share of headaches with conky XD You add one thing, and it pushes something else down; you remove one thing, and it pulls something up; change the size of something, and you messed it up again etc etc... A real mess :angry:

---

The basic idea is that there are no absolute position statements for anything other than images.
The first voffset looks at the top of the conky window, the second voffset looks at the fist line, the third looks at the second line, etc...

Think of CSS (if you are familiar with it). Everything other than images is in the document flow and has `position: relative`, while images are not in the flow and have `position: fixed` (ie. they are positioned relative to the conky window).

**Comment by VicenteRD** [comment]
http://i.imgur.com/B20xf31.png Got it :D . Still, no fancy weather picture, but got the other thing done

**Comment by zagortenay333** [comment]
Yeah I think I removed the picture mode from new-minty.
