### ISSUE TITLE
Arc theme

### ISSUE THREAD

**Issue by bilelmoussaoui** [zagortenay333/Harmattan#9]
Please add an arc theme :D

**Comment by zagortenay333** [comment]
If I'm not too lazy, I will. :smile:

**Comment by elmagio** [comment]
Guessing you've been too lazy up until now. :smile:

**Comment by zagortenay333** [comment]
@elmagio this commit disagrees 32c576fbdc57a0ec6050eb8340f11f9abd42e740

**Comment by elmagio** [comment]
Sorry if it came out obnoxious, was trying to revive this topic with a lighthearted joke. :sweatdrop:

**Comment by zagortenay333** [comment]
I know that's why I added a smile to your comments. Oh, theres a like button on github now. :+1:

**Comment by zagortenay333** [comment]
Let's face it.. I will never be not lazy for this. I'll close this so I don't get even more depressed about it. lmao

Besides, it's annoying when you make a theme for another actively developed project because then you have to keep maintaining it.  
I already regret having made themes for my own Ciliora themes which I updated countless times ever since I made Harmattan.
